# Generated by Django 3.1.6 on 2021-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('user_id', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
