# Generated by Django 3.1.6 on 2021-02-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='start_datetime',
        ),
    ]
