# Generated by Django 3.1.6 on 2021-02-13 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210213_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 17, 14, 4, 825945)),
        ),
    ]
